/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Root */
    get: operations['read_root__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations['health_check_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/image-processing': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Saved Images */
    get: operations['get_saved_images_api_image_processing_get'];
    put?: never;
    /** Img Processing */
    post: operations['img_processing_api_image_processing_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/image-processing/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Img Processing Save */
    post: operations['img_processing_save_api_image_processing_save_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_img_processing_api_image_processing_post */
    Body_img_processing_api_image_processing_post: {
      /** File */
      file: string;
      /**
       * Prctype
       * @enum {string}
       */
      prcType:
        | 'sobel'
        | 'prewitt'
        | 'laplacian'
        | 'gaussian'
        | 'blur'
        | 'gaussianBlur'
        | 'medianBlur'
        | 'bilateralFilter'
        | 'findContour'
        | 'plus'
        | 'minus'
        | 'binary'
        | 'inverse'
        | 'tozero'
        | 'tozeroInverse';
      /** Kernelsize */
      kernelSize?: number | null;
    };
    /** Body_img_processing_save_api_image_processing_save_post */
    Body_img_processing_save_api_image_processing_save_post: {
      /** Blob */
      blob: string;
      /** Prctype */
      prcType: string;
    };
    /** FileListItem */
    FileListItem: {
      /** Id */
      id: string;
      /** Originnm */
      originNm: string;
      /** Nm */
      nm: string;
      /** Path */
      path: string;
      /** Mimetype */
      mimeType: string;
      /** Sizebytes */
      sizeBytes: number;
      /**
       * Uploadedat
       * Format: date-time
       */
      uploadedAt: string;
      /** Options */
      options: {
        [key: string]: string;
      };
    };
    /** FileListResponse */
    FileListResponse: {
      /** Items */
      items: components['schemas']['FileListItem'][];
      /** Hasmore */
      hasMore: boolean;
      /** Nextcursoruploadedat */
      nextCursorUploadedAt?: string | null;
      /** Nextcursorid */
      nextCursorId?: string | null;
    };
    /** FileSaveResponse */
    FileSaveResponse: {
      /** Id */
      id: string;
      /** Originnm */
      originNm: string;
      /** Nm */
      nm: string;
      /** Path */
      path: string;
      /** Mimetype */
      mimeType: string;
      /** Sizebytes */
      sizeBytes: number;
      /**
       * Uploadedat
       * Format: date-time
       */
      uploadedAt: string;
      /** Options */
      options: {
        [key: string]: string;
      };
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  read_root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  health_check_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  get_saved_images_api_image_processing_get: {
    parameters: {
      query?: {
        limit?: number;
        cursorUploadedAt?: string | null;
        cursorId?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FileListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  img_processing_api_image_processing_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_img_processing_api_image_processing_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  img_processing_save_api_image_processing_save_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_img_processing_save_api_image_processing_save_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FileSaveResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
