/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const NODE_SIZE_PRESETS: typeof import('./stores/settings-store').NODE_SIZE_PRESETS
  const SOURCE_NODE_ID: typeof import('./composables/useFilterGraph').SOURCE_NODE_ID
  const collectDescendantLeaves: typeof import('./composables/useFilterGraph').collectDescendantLeaves
  const collectPathToNode: typeof import('./composables/useFilterGraph').collectPathToNode
  const computeViewportStatus: typeof import('./composables/useCropManager').computeViewportStatus
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const stores: typeof import('./stores/index').default
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCounterStore: typeof import('./stores/example-store').useCounterStore
  const useCropManager: typeof import('./composables/useCropManager').useCropManager
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useFilterGraph: typeof import('./composables/useFilterGraph').useFilterGraph
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useNodeResize: typeof import('./composables/useNodeResize').useNodeResize
  const useOriginImage: typeof import('./composables/useOriginImage').useOriginImage
  const useParamCompletion: typeof import('./composables/useParamCompletion').useParamCompletion
  const usePresetMgr: typeof import('./composables/usePresetMgr').usePresetMgr
  const usePreviewManager: typeof import('./composables/usePreviewManager').usePreviewManager
  const useProcessMgr: typeof import('./composables/useProcessMgr').useProcessMgr
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSettingsStore: typeof import('./stores/settings-store').useSettingsStore
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useThumbnailProcessor: typeof import('./composables/useThumbnailProcessor').useThumbnailProcessor
  const useZoomPopup: typeof import('./composables/useZoomPopup').useZoomPopup
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { CropItem } from './composables/useCropManager'
  import('./composables/useCropManager')
  // @ts-ignore
  export type { FilterGraphCallbacks } from './composables/useFilterGraph'
  import('./composables/useFilterGraph')
  // @ts-ignore
  export type { OriginData } from './composables/useOriginImage'
  import('./composables/useOriginImage')
  // @ts-ignore
  export type { TempStep } from './composables/usePreviewManager'
  import('./composables/usePreviewManager')
  // @ts-ignore
  export type { ZoomPopup } from './composables/useZoomPopup'
  import('./composables/useZoomPopup')
  // @ts-ignore
  export type { PiniaCustomProperties } from './stores/index'
  import('./stores/index')
  // @ts-ignore
  export type { NodeSizeKey } from './stores/settings-store'
  import('./stores/settings-store')
}
