/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    BeforeAfterSlider: typeof import('./components/flow/BeforeAfterSlider.vue')['default']
    CropDialog: typeof import('./components/dialog/CropDialog.vue')['default']
    CropListPanel: typeof import('./components/sidebar/CropListPanel.vue')['default']
    CustomFilterEditorDialog: typeof import('./components/dialog/CustomFilterEditorDialog.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    FilterListPanel: typeof import('./components/sidebar/FilterListPanel.vue')['default']
    FilterNode: typeof import('./components/flow/FilterNode.vue')['default']
    FilterTreeSelect: typeof import('./components/flow/FilterTreeSelect.vue')['default']
    ImageGalleryDialog: typeof import('./components/dialog/ImageGalleryDialog.vue')['default']
    ImageZoomPopup: typeof import('./components/flow/ImageZoomPopup.vue')['default']
    LocalImportDialog: typeof import('./components/dialog/LocalImportDialog.vue')['default']
    OsdViewer: typeof import('./components/flow/OsdViewer.vue')['default']
    ParamField: typeof import('./components/flow/ParamField.vue')['default']
    ParamPanel: typeof import('./components/flow/ParamPanel.vue')['default']
    PresetListPanel: typeof import('./components/sidebar/PresetListPanel.vue')['default']
    PresetSaveDialog: typeof import('./components/dialog/PresetSaveDialog.vue')['default']
    ProcessListPanel: typeof import('./components/sidebar/ProcessListPanel.vue')['default']
    ProcessSaveDialog: typeof import('./components/dialog/ProcessSaveDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./components/dialog/SettingsDialog.vue')['default']
    SourceNode: typeof import('./components/flow/SourceNode.vue')['default']
    TimelineViewer: typeof import('./components/flow/TimelineViewer.vue')['default']
    ZoomableImage: typeof import('./components/flow/ZoomableImage.vue')['default']
    ZoomSidePanel: typeof import('./components/flow/ZoomSidePanel.vue')['default']
  }
}
